import {Router} from 'express';import {z} from 'zod';import {prisma} from '../lib/prisma.js';import {login,createSessionForApproved,completeLoginChallenge,registerStudent} from '../services/auth.js';import {requestOtp} from '../services/otp.js';import {hashPassword,randomToken,sha256} from '../lib/security.js';import {env} from '../config/env.js';import {cookieOptions} from '../middleware/security.js';import {ok,fail} from '../lib/http.js';import {requireAuth,type AuthRequest} from '../middleware/auth.js';import {audit} from '../services/audit.js';
const r=Router();const loginSchema=z.object({email:z.string().min(1),password:z.string().min(1),rememberDevice:z.boolean().optional(),deviceName:z.string().optional(),os:z.string().optional(),browser:z.string().optional()});
r.post('/register',async(req,res,next)=>{try{
 const p=z.object({email:z.string().email(),phone:z.string().min(10).max(15),password:z.string().min(8),confirmPassword:z.string().min(8)}).parse(req.body);
 if(p.password!==p.confirmPassword)return fail(res,400,'VALIDATION_ERROR','Passwords do not match');
 const result=await registerStudent({email:p.email,phone:p.phone,password:p.password});
 try{
   const otp=await requestOtp({method:'EMAIL',recipient:p.email,purpose:'REGISTRATION',ipAddress:req.ip ?? '',userAgent:req.get('user-agent')});
   return res.status(201).json({success:true,data:{...result,verificationRequired:true,resendAvailableAt:otp.resendAvailableAt,expiresAt:otp.expiresAt},requestId:res.locals.requestId});
 }catch(e){
   await prisma.user.delete({where:{publicId:result.userId}}).catch(()=>undefined);
   throw e;
 }
 }catch(e){const code=e instanceof Error?e.message:'';if(code==='EMAIL_ALREADY_REGISTERED')return fail(res,409,code,'Email is already registered');if(code==='PHONE_ALREADY_REGISTERED')return fail(res,409,code,'Mobile number is already registered');if(code==='COLLEGE_NOT_CONFIGURED')return fail(res,503,code,'Student registration is temporarily unavailable');next(e)}});

r.post('/login',async(req,res,next)=>{try{
 const p=z.object({identifier:z.string().min(1).optional(),email:z.string().min(1).optional(),password:z.string().min(1),rememberDevice:z.boolean().optional(),deviceName:z.string().optional(),os:z.string().optional(),browser:z.string().optional()}).refine(v=>!!(v.identifier||v.email),{message:'Email or mobile number is required'}).parse(req.body);
 const result=await login({email:p.identifier||p.email||'',password:p.password,rememberDevice:p.rememberDevice,deviceName:p.deviceName,os:p.os,browser:p.browser,ip:req.ip ?? '',userAgent:req.get('user-agent')||'',requestId:res.locals.requestId?String(res.locals.requestId):undefined});
 if(result.kind==='invalid')return fail(res,401,'AUTH_INVALID_CREDENTIALS','Invalid credentials');
 if(result.kind==='locked')return fail(res,423,'AUTH_ACCOUNT_LOCKED','Account temporarily locked');
 if(result.kind==='pending_verification')return fail(res,403,'AUTH_REGISTRATION_NOT_VERIFIED','Please verify your registration OTP before logging in');if(result.kind==='forbidden')return fail(res,403,'AUTH_FORBIDDEN','Account access is restricted');
 if(result.kind==='device_rejected')return fail(res,403,'AUTH_DEVICE_REJECTED','This device is not allowed');
 if(result.kind==='otp_required'){
  if(!result.user)return fail(res,500,'AUTH_ERROR','Authentication user data is unavailable');
  res.cookie(env.LOGIN_CHALLENGE_COOKIE_NAME,result.challengeToken,{httpOnly:true,secure:env.NODE_ENV==='production',sameSite:env.COOKIE_SAME_SITE,path:'/',maxAge:10*60*1000});
  return ok(res,{status:'OTP_REQUIRED',role:result.user.role,email:result.user.email,phone:result.user.student?.phone||null});
}
 return fail(res,500,'AUTH_ERROR','Unexpected authentication result');
}catch(e){next(e)}});

r.post('/login/complete',async(req,res,next)=>{try{
 const raw=req.cookies?.[env.LOGIN_CHALLENGE_COOKIE_NAME] as string|undefined;if(!raw)return fail(res,401,'AUTH_LOGIN_CHALLENGE_EXPIRED','Login verification expired. Please login again.');
 const p=z.object({rememberDevice:z.boolean().optional()}).parse(req.body||{});
 const result=await completeLoginChallenge(raw,{ip:req.ip??'',userAgent:req.get('user-agent')||'',rememberDevice:p.rememberDevice});
 if(!result)return fail(res,401,'AUTH_LOGIN_CHALLENGE_EXPIRED','Login verification expired. Please login again.');
 res.cookie(env.SESSION_COOKIE_NAME,result.raw,{...cookieOptions(),maxAge:result.expires.getTime()-Date.now()});
 res.clearCookie(env.LOGIN_CHALLENGE_COOKIE_NAME,{httpOnly:true,secure:env.NODE_ENV==='production',sameSite:env.COOKIE_SAME_SITE,path:'/'});
 return ok(res,{status:'AUTHENTICATED',role:result.role});
}catch(e){next(e)}});

r.post('/logout',requireAuth,async(req:AuthRequest,res,next)=>{try{await prisma.session.update({where:{id:req.auth!.sessionId},data:{revokedAt:new Date()}});await prisma.loginHistory.create({data:{userId:req.auth!.userId,deviceId:req.auth!.deviceId,event:'LOGOUT',status:'SUCCESS',ipAddress:req.ip ?? '',userAgent:req.get('user-agent')}});await audit({actorUserId:req.auth!.userId,actorRole:req.auth!.role as any,action:'LOGOUT',entityType:'Session',entityId:req.auth!.sessionId,requestId:res.locals.requestId});res.clearCookie(env.SESSION_COOKIE_NAME,cookieOptions());return ok(res,{loggedOut:true});}catch(e){next(e)}});
r.post('/logout-all',requireAuth,async(req:AuthRequest,res,next)=>{try{await prisma.$transaction(async tx=>{await tx.session.updateMany({where:{userId:req.auth!.userId,revokedAt:null},data:{revokedAt:new Date()}});await tx.loginHistory.create({data:{userId:req.auth!.userId,event:'LOGOUT_ALL',status:'SUCCESS',ipAddress:req.ip ?? '',userAgent:req.get('user-agent')}})});await audit({actorUserId:req.auth!.userId,actorRole:req.auth!.role as any,action:'LOGOUT_ALL',requestId:res.locals.requestId});res.clearCookie(env.SESSION_COOKIE_NAME,cookieOptions());return ok(res,{loggedOut:true});}catch(e){next(e)}});
r.post('/refresh',requireAuth,async(req:AuthRequest,res,next)=>{try{const s=await prisma.session.findUnique({where:{id:req.auth!.sessionId}});if(!s)return fail(res,401,'AUTH_SESSION_EXPIRED','Session expired');const raw=randomToken(48);await prisma.session.update({where:{id:s.id},data:{tokenHash:sha256(raw),expiresAt:new Date(Date.now()+30*86400000)}});res.cookie(env.SESSION_COOKIE_NAME,raw,{...cookieOptions(),maxAge:30*86400000});return ok(res,{refreshed:true});}catch(e){next(e)}});
r.post('/login-request/:id/status',async(req,res,next)=>{try{const p=z.object({pollToken:z.string().min(20)}).parse(req.body);const id = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id; if(!id) return fail(res,400,'VALIDATION_ERROR','Invalid login request id'); const lr=await prisma.loginRequest.findFirst({where:{publicId:id,expiresAt:{gt:new Date()}},include:{user:true,device:true}});if(!lr)return fail(res,404,'DEVICE_REQUEST_EXPIRED','Login request not found or expired');if(sha256(p.pollToken)!==String((lr as any).pollTokenHash))return fail(res,403,'AUTH_FORBIDDEN','Invalid login request token');if(lr.status==='PENDING')return ok(res,{status:'PENDING_DEVICE_APPROVAL'});if(lr.status==='REJECTED')return fail(res,403,'AUTH_DEVICE_REJECTED','This device login was rejected');if(lr.status!=='APPROVED')return fail(res,409,'AUTH_DEVICE_APPROVAL_REQUIRED','Login request is not approved');if(lr.sessionIssuedAt)return fail(res,409,'AUTH_SESSION_EXPIRED','Login request has already been completed');const raw=randomToken(48);const expires=new Date(Date.now()+30*86400000);const claimed=await prisma.$transaction(async tx=>{const updated=await tx.loginRequest.updateMany({where:{id:lr.id,status:'APPROVED',sessionIssuedAt:null},data:{sessionIssuedAt:new Date()}});if(updated.count!==1)return null;const session=await tx.session.create({data:{userId:lr.userId,deviceId:lr.deviceId,tokenHash:sha256(raw),expiresAt:expires,ipAddress:lr.ipAddress,userAgent:lr.userAgent,remembered:true}});await tx.user.update({where:{id:lr.userId},data:{lastLoginAt:new Date()}});await tx.device.update({where:{id:lr.deviceId},data:{lastSeenAt:new Date()}});await tx.loginHistory.create({data:{userId:lr.userId,deviceId:lr.deviceId,event:'LOGIN_SUCCESS',status:'SUCCESS',ipAddress:lr.ipAddress ?? '',userAgent:lr.userAgent}});return session;});if(!claimed)return fail(res,409,'AUTH_SESSION_EXPIRED','Login request has already been completed');res.cookie(env.SESSION_COOKIE_NAME,raw,{...cookieOptions(),maxAge:expires.getTime()-Date.now()});await audit({actorUserId:lr.userId,actorRole:lr.user?.role as any,action:'LOGIN',entityType:'Session',entityId:claimed.id,requestId:res.locals.requestId});return ok(res,{status:'AUTHENTICATED',role:lr.user?.role});}catch(e){next(e)}});
r.get('/me',requireAuth,async(req:AuthRequest,res,next)=>{try{const user=await prisma.user.findUnique({where:{id:req.auth!.userId},select:{publicId:true,email:true,role:true,status:true,student:{include:{college:true,parent:true,hostel:true,room:true,bed:true}}}});return ok(res,{user});}catch(e){next(e)}});
r.post('/forgot-password',async(req,res,next)=>{try{const email=z.object({email:z.string().email()}).parse(req.body).email.toLowerCase();const data=await requestOtp({method:'EMAIL',recipient:email,purpose:'PASSWORD_RESET',ipAddress:req.ip ?? '',userAgent:req.get('user-agent')});return ok(res,data);}catch(e){const code=e instanceof Error?e.message:'';if(code==='OTP_RESEND_COOLDOWN')return fail(res,429,code,'Please wait before requesting another OTP');if(code==='OTP_RATE_LIMITED')return fail(res,429,code,'Too many OTP requests. Please try again later.');if(code==='OTP_DELIVERY_FAILED')return fail(res,502,code,'We could not deliver the verification code. Please try again later.');return next(e)}});
r.post('/reset-password',async(req,res,next)=>{try{const body=z.object({userId:z.string().uuid().optional(),token:z.string().min(20).optional(),newPassword:z.string().min(8)}).parse(req.body);const cookieToken=req.cookies?.[env.PASSWORD_RESET_COOKIE_NAME] as string|undefined;const rawToken=body.token||cookieToken;if(!rawToken)return fail(res,400,'VALIDATION_ERROR','Password reset verification is required');const token=await prisma.passwordResetToken.findFirst({where:{...(body.userId?{userId:body.userId}:{}),tokenHash:sha256(rawToken),usedAt:null,expiresAt:{gt:new Date()}}});if(!token)return fail(res,400,'VALIDATION_ERROR','Password reset verification is invalid or expired');await prisma.$transaction(async tx=>{await tx.user.update({where:{id:token.userId},data:{passwordHash:await hashPassword(body.newPassword),lastPasswordChangedAt:new Date()}});await tx.session.updateMany({where:{userId:token.userId,revokedAt:null},data:{revokedAt:new Date()}});await tx.passwordResetToken.update({where:{id:token.id},data:{usedAt:new Date()}})});res.clearCookie(env.PASSWORD_RESET_COOKIE_NAME,{httpOnly:true,secure:env.NODE_ENV==='production',sameSite:env.COOKIE_SAME_SITE,path:'/'});await audit({actorUserId:token.userId,action:'PASSWORD_CHANGED',requestId:res.locals.requestId});return ok(res,{requiresLogin:true});}catch(e){next(e)}});
export default r;
