import {Router} from 'express';import {requireAuth,requireRole,type AuthRequest} from '../middleware/auth.js';import {ok,fail} from '../lib/http.js';import {prisma} from '../lib/prisma.js';import {sha256} from '../lib/security.js';import {audit} from '../services/audit.js';
const r=Router();
async function verify(req:AuthRequest,res:any){const token=String(req.body.qrToken||'');const t=await prisma.qRToken.findFirst({where:{tokenHash:sha256(token)},include:{student:{include:{hostel:true,room:true}}}});if(!t)return fail(res,404,'QR_INVALID','QR_INVALID');if(t.expiresAt<new Date())return fail(res,410,'QR_EXPIRED','QR_EXPIRED');if(t.status==='REVOKED')return fail(res,410,'QR_REVOKED','QR_REVOKED');if(t.status==='USED'&&t.purpose!=='ID_VERIFY')return fail(res,410,'QR_ALREADY_USED','QR_ALREADY_USED');if(t.student.status!=='ACTIVE')return fail(res,403,'QR_STUDENT_INACTIVE','QR_STUDENT_INACTIVE');await audit({actorUserId:req.auth!.userId,actorRole:req.auth!.role as any,action:'QR_VERIFIED',entityType:'QRToken',entityId:t.id,requestId:res.locals.requestId});return ok(res,{status:'STUDENT_VERIFIED',student:{name:t.student.name,enrollmentId:t.student.enrollmentId,hostel:t.student.hostel?.name,room:t.student.room?.roomNumber,photoUrl:t.student.photoUrl},verifiedAt:new Date()});}
r.post('/rector/qr/verify',requireAuth,requireRole('RECTOR','ADMIN'),verify);r.post('/security/qr/verify',requireAuth,requireRole('SECURITY','ADMIN'),verify);
r.get('/rector/attendance',requireAuth,requireRole('RECTOR','ADMIN'),async(req:AuthRequest,res)=>ok(res,{items:await prisma.attendance.findMany({orderBy:{markedAt:'desc'},take:100})}));
r.get('/rector/applications',requireAuth,requireRole('RECTOR','ADMIN'),async(req,res)=>ok(res,{items:await prisma.application.findMany({orderBy:{createdAt:'desc'},take:100})}));
r.get('/rector/complaints',requireAuth,requireRole('RECTOR','ADMIN'),async(req,res)=>ok(res,{items:await prisma.complaint.findMany({orderBy:{createdAt:'desc'},take:100})}));
r.get('/security/vehicles/:vehicleUniqueId',requireAuth,requireRole('SECURITY','ADMIN'),async(req,res)=>{const vehicleUniqueId = Array.isArray(req.params.vehicleUniqueId) ? req.params.vehicleUniqueId[0] : req.params.vehicleUniqueId; if(!vehicleUniqueId) return fail(res,400,'VALIDATION_ERROR','Invalid vehicle id'); const v=await prisma.vehicle.findUnique({where:{vehicleUniqueId}});if(!v)return fail(res,404,'VEHICLE_NOT_FOUND','Vehicle not found'); const student = v.studentId ? await prisma.student.findUnique({where:{id:v.studentId}, include:{hostel:true, room:true}}) : null; return ok(res,{vehicle:{vehicleUniqueId:v.vehicleUniqueId,vehicleNumber:v.vehicleNumber,vehicleType:v.vehicleType,status:v.status,owner:v.ownerNameSnapshot,studentName:student?.name,hostel:student?.hostel?.name,room:student?.room?.roomNumber}})});
export default r;
